name: Sauce Connect
description: Runs sauce-connect for a given step
author: https://github.com/joscha
requirements:
  - buildkite-agent
  - bash
  - curl
  - unzip
  - sleep
public: true
configuration:
  properties:
    tunnel-identifier:
      type: string
    sauce-connect-version:
      type: string
    force-upload-logs:
      type: boolean
  required: []
  additionalProperties: false
