name: Sauce Connect
description: Runs sauce-connect for a given step
author: https://github.com/joscha
requirements:
  - buildkite-agent
public: true
configuration:
  properties:
    tunnel-identifier:
      type: string
    sauce-connect-version:
      type: string
  required: []
  additionalProperties: false