steps:
  - label: ":hammer: test"
    plugins:
      docker-compose#v1.3.1:
        run: tests
  - label: ":sparkles: lint"
    plugins:
      plugin-linter#v1.0.0:
        name: sauce-connect
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**
